- name: Reboot
  ansible.builtin.reboot:

- name: Netplan apply
  ansible.builtin.command: netplan apply
  async: 45
  poll: 0
  changed_when: false

- name: Restart fail2ban
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    enabled: true
    name: fail2ban