---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - ansible.builtin.apt:
        name:
          - ssh
          - ufw
        state: present
        force_apt_get: true
        purge: true
