---
- name: SET IP | Configuring netplan for static IP
  ansible.builtin.template:
    src: templates/netplan.j2
    dest: /etc/netplan/00-installer-config.yaml
    owner: root
    group: root
    mode: '0644'
  register: netplan_template

- name: SET IP | Apply netplan
  ansible.builtin.command: netplan apply
  async: 45
  poll: 0
  when: netplan_template.changed
