---
- name: SET IP | Configuring netplan for static IP
  ansible.builtin.template:
    src: templates/netplan.j2
    dest: /etc/netplan/00-installer-config.yaml
    owner: root
    group: root
    mode: '0644'
  notify:
    - Netplan apply
